-- 1. EXTENSIONS & CORE TABLE
create extension if not exists "pgcrypto";

create table if not exists public.menu_products (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    short_description text not null,
    image_url text not null,
    type text not null,
    collection text not null,
    occasion text[] not null default '{}',
    order_style text not null,
    method text,                       -- The "Crunch Factor" column
    preferences text[] not null default '{}',
    volume text[] not null default '{}',
    bestsellers text[] not null default '{}', -- The "Oby's Special" column
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

-- 2. AUTOMATIC TIMESTAMPS
create or replace function public.set_menu_products_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists menu_products_set_updated_at on public.menu_products;
create trigger menu_products_set_updated_at
before update on public.menu_products
for each row execute function public.set_menu_products_updated_at();

-- 3. ROW LEVEL SECURITY (DATABASE)
alter table public.menu_products enable row level security;

-- Public Menu Access (menu.html)
drop policy if exists "Public can view active menu products" on public.menu_products;
create policy "Public can view active menu products"
on public.menu_products for select using (is_active = true);

-- Admin Access (admin.html using anon key)
drop policy if exists "Anon can manage all menu products" on public.menu_products;
create policy "Anon can manage all menu products"
on public.menu_products for select to anon using (true);

drop policy if exists "Anon can insert menu products" on public.menu_products;
create policy "Anon can insert menu products"
on public.menu_products for insert to anon with check (true);

drop policy if exists "Anon can update menu products" on public.menu_products;
create policy "Anon can update menu products"
on public.menu_products for update to anon using (true) with check (true);

drop policy if exists "Anon can delete menu products" on public.menu_products;
create policy "Anon can delete menu products"
on public.menu_products for delete to anon using (true);

-- 4. REALTIME BROADCAST
do $$
begin
    if not exists (
        select 1 from pg_publication_tables 
        where pubname = 'supabase_realtime' 
        and schemaname = 'public' and tablename = 'menu_products'
    ) then
        alter publication supabase_realtime add table public.menu_products;
    end if;
end $$;

-- 5. STORAGE BUCKET & POLICIES
insert into storage.buckets (id, name, public)
values ('menu-products', 'menu-products', true)
on conflict (id) do nothing;

-- Public View Images
drop policy if exists "Public can view menu product images" on storage.objects;
create policy "Public can view menu product images"
on storage.objects for select using (bucket_id = 'menu-products');

-- Admin Upload/Edit/Delete
drop policy if exists "Anon can upload menu product images" on storage.objects;
create policy "Anon can upload menu product images"
on storage.objects for insert to anon with check (bucket_id = 'menu-products');

drop policy if exists "Anon can update menu product images" on storage.objects;
create policy "Anon can update menu product images"
on storage.objects for update to anon using (bucket_id = 'menu-products') with check (bucket_id = 'menu-products');

drop policy if exists "Anon can delete menu product images" on storage.objects;
create policy "Anon can delete menu product images"
on storage.objects for delete to anon using (bucket_id = 'menu-products');

-- 6. CACHE REFRESH (The "Schema Cache" Fix)
notify pgrst, 'reload schema';
-- 1. Ensure the 'method' column exists with the correct type
-- This supports the "Fried vs. Baked" filter for Fransmore
ALTER TABLE public.menu_products 
ADD COLUMN IF NOT EXISTS method text;

-- 2. CRITICAL: Refresh the PostgREST cache
-- This is the specific command that clears the "Could not find column" error
NOTIFY pgrst, 'reload schema';

-- 3. Verify Realtime is still active for the updated table
DO $$ 
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables 
        WHERE pubname = 'supabase_realtime' 
        AND schemaname = 'public' 
        AND tablename = 'menu_products'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.menu_products;
    END IF;
END $$;
-- 1. Ensure the 'slug' column exists with the correct constraints
-- This is vital for the Lagos-based digital-first market strategy
ALTER TABLE public.menu_products 
ADD COLUMN IF NOT EXISTS slug text NOT NULL UNIQUE;

-- 2. THE FIX: Force the API to reload the schema cache
-- This clears the "Could not find slug column" error immediately
NOTIFY pgrst, 'reload schema';

-- 3. Verify the 'method' and 'bestsellers' columns are also recognized
-- These support the "Crunch Factor" and "Oby's Special" filters
ALTER TABLE public.menu_products 
ADD COLUMN IF NOT EXISTS method text,
ADD COLUMN IF NOT EXISTS bestsellers text[] DEFAULT '{}';

-- 4. Re-run the cache refresh one more time to be safe
NOTIFY pgrst, 'reload schema';